@startuml

class User {
    firstName: string
    lastName: string
    email: string
}

class Client {

}

class Lawyer {
    yearsOfExperience: number
    experiencedSubjectMatters: LawSubjectMatter[]
    experiencedExamples: LawSubjectMatterExample[]
}

class LawSubjectMatter {
    subjectName: string
    subjectDescription: string
    lawSubjectMatterExamples: LawSubjectMatterExample[]
}

class LawSubjectMatterExample {
    exampleName: string
    exampleDescription: string
}

class LegalServiceCategory {
    serviceName: string
    serviceDescription: string
}

class LawyerServiceCosting {
    lawSubjectMatter: LawSubjectMatter
    specificExamples: LawSubjectMatterExample[]
    estimatedCostLowerBound: number
    estimatedCostHigherBound: number
    lawyer: Lawyer
}

class CaseTemplate {
    lawSubjectMatter: LawSubjectMatter
    associatedExamples: LawSubjectMatterExample[]
    createdByLawyer: Lawyer
    documents: Document[]
    requiredFields: map
}

class Document {
    documentName: string
    documentDescription: string
    documentURL: string
}

class Case {

}

note left of LawSubjectMatter 
Civil
- Small claims, Employment claims, Neighbour disputes, Bankruptcy, Breach of contract, Commercial disputes
Criminal
- Homicide, Drug offences, Sexual offences, Cheating, Traffic or regulatory offences.
Family
- Divorce, Family violence, Probate and administration, Maintenance, Adoption, Child protection.
end note

note right of LegalServiceCategory::serviceDescription
- Consultation for legal advice or the review of documents (e.g. wills, leases, and agreements).
- Mediation to help disputing parties to reach a mutually agreeable settlement.
- Arbitration to make a binding decision to settle a dispute.
- Preparation of legal documents.
- Representation of clients in negotiations, court, or arbitration.
end note

@enduml